
import { createClient } from '@supabase/supabase-js';

/*
-- =================================================================
-- SUPABASE PORTAL SCHEMA SETUP
-- =================================================================
-- Instructions:
-- 1. Go to your Supabase project dashboard.
-- 2. Navigate to the "SQL Editor".
-- 3. Click "+ New query".
-- 4. Copy the entire script below and paste it into the editor.
-- 5. Click "RUN".
--
-- This script is idempotent, meaning you can run it multiple times
-- without causing errors. It will create tables if they don't exist
-- and add missing columns/constraints.
-- =================================================================

-- Table: portal_users
-- Stores profiles for students and teachers.
CREATE TABLE IF NOT EXISTS public.portal_users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text UNIQUE,
    role text DEFAULT 'student'::text NOT NULL,
    enrollment_id text UNIQUE,
    password text
);

-- Add the 'phone' column for OTP verification if it's missing.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'portal_users' AND column_name = 'phone'
    ) THEN
        ALTER TABLE public.portal_users ADD COLUMN phone text;
    END IF;
END $$;


-- Table: portal_sessions
-- Stores QR code attendance sessions created by teachers.
CREATE TABLE IF NOT EXISTS public.portal_sessions (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    teacher_id bigint,
    is_active boolean DEFAULT true NOT NULL
);

-- Add foreign key to portal_sessions to link to a teacher.
-- ON DELETE SET NULL preserves attendance history if a teacher account is removed.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'portal_sessions_teacher_id_fkey') THEN
        ALTER TABLE public.portal_sessions
        ADD CONSTRAINT portal_sessions_teacher_id_fkey
        FOREIGN KEY (teacher_id) REFERENCES public.portal_users(id) ON DELETE SET NULL;
    END IF;
END $$;


-- Table: portal_attendance
-- Logs student check-ins for each session.
CREATE TABLE IF NOT EXISTS public.portal_attendance (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    student_id bigint,
    session_id uuid
);

-- Add foreign key for student_id. ON DELETE CASCADE removes attendance if a student is deleted.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'portal_attendance_student_id_fkey') THEN
        ALTER TABLE public.portal_attendance
        ADD CONSTRAINT portal_attendance_student_id_fkey
        FOREIGN KEY (student_id) REFERENCES public.portal_users(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Add foreign key for session_id. ON DELETE CASCADE removes attendance if a session is deleted.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'portal_attendance_session_id_fkey') THEN
        ALTER TABLE public.portal_attendance
        ADD CONSTRAINT portal_attendance_session_id_fkey
        FOREIGN KEY (session_id) REFERENCES public.portal_sessions(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Add a UNIQUE constraint to prevent a student from checking in more than once per session.
-- This is necessary for ON CONFLICT clauses to work and prevents data duplication.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'portal_attendance_student_session_unique') THEN
        ALTER TABLE public.portal_attendance
        ADD CONSTRAINT portal_attendance_student_session_unique
        UNIQUE (student_id, session_id);
    END IF;
END $$;


-- RLS (Row Level Security) is not managed by this script to keep things simple.
-- If you enable RLS, you must create policies for each table to allow access.

-- Insert a default teacher if one doesn't exist.
-- Replace with your own details.
INSERT INTO public.portal_users (name, email, role, password)
VALUES ('Teacher', 'teacher@example.com', 'teacher', 'password123')
ON CONFLICT (email) DO NOTHING;
*/

// FIX: Define database types for Supabase to enable type safety
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      portal_attendance: {
        Row: {
          created_at: string
          id: number
          session_id: string | null
          student_id: number | null
        }
        Insert: {
          created_at?: string
          id?: number
          session_id?: string | null
          student_id?: number | null
        }
        Update: {
          created_at?: string
          id?: number
          session_id?: string | null
          student_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "portal_attendance_session_id_fkey"
            columns: ["session_id"]
            referencedRelation: "portal_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "portal_attendance_student_id_fkey"
            columns: ["student_id"]
            referencedRelation: "portal_users"
            referencedColumns: ["id"]
          }
        ]
      }
      portal_sessions: {
        Row: {
          created_at: string
          expires_at: string
          id: string
          is_active: boolean
          teacher_id: number | null
        }
        Insert: {
          created_at?: string
          expires_at: string
          id?: string
          is_active?: boolean
          teacher_id?: number | null
        }
        Update: {
          created_at?: string
          expires_at?: string
          id?: string
          is_active?: boolean
          teacher_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "portal_sessions_teacher_id_fkey"
            columns: ["teacher_id"]
            referencedRelation: "portal_users"
            referencedColumns: ["id"]
          }
        ]
      }
      portal_users: {
        Row: {
          created_at: string
          email: string | null
          enrollment_id: string | null
          id: number
          name: string
          password: string | null
          phone: string | null
          role: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          enrollment_id?: string | null
          id?: number
          name: string
          password?: string | null
          phone?: string | null
          role?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          enrollment_id?: string | null
          id?: number
          name?: string
          password?: string | null
          phone?: string | null
          role?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}


// --- Supabase Configuration ---
const supabaseUrl = 'https://djgnzprigxgbloruuayw.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZ256cHJpZ3hnYmxvcnV1YXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTk5MDgsImV4cCI6MjA3MjE5NTkwOH0.sbFsHtBPNhi-4-ZJ90w-4SYl49lesWhzXKHuwTRz2hc';

let supabase: ReturnType<typeof createClient<Database>> | null = null;

const isUrlPlaceholder = supabaseUrl.includes('YOUR_SUPABASE_URL');
const isKeyPlaceholder = supabaseAnonKey.includes('YOUR_SUPABASE_ANON_KEY');

if (!isUrlPlaceholder && !isKeyPlaceholder) {
    try {
        // FIX: Pass the Database generic to createClient for type safety
        supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);
    } catch (e) {
        console.error("Supabase initialization error:", e);
        supabase = null;
    }
} else {
    console.error("Supabase is not configured. Please add your credentials to components/firebase-config.ts and run the SQL script provided in the comments to enable the real-time portal.");
}

export { supabase };
